import org.junit.jupiter.api.Test;

import java.time.Duration;
import java.time.LocalDateTime;
import java.time.Month;

import static org.junit.jupiter.api.Assertions.*;

class InMemoryTaskManagerTest extends TaskManagerTest<InMemoryTaskManager> {
    @Override
    protected InMemoryTaskManager createTaskManager() {
        return (InMemoryTaskManager) Managers.getDefault();
    }

    @Test
    public void shouldNotConflictBetweenManualAndAutoGeneratedIds() {
        TaskManager taskManager = createTaskManager();
        Task task = new Task("Задача 1", "Описание задачи 1", durationForTask, startTimeForTask);
        Task manualTask = new Task("Задача 2", "Описание задачи 2", 3, durationForTask.plusDays(10), startTimeForTask.minusHours(1).plusDays(5).minusYears(2));
        assertNotEquals(manualTask.getId(), task.getId());
    }
}